SUBDIRS = src emu examples doc
dist_doc_DATA = README INSTALL ChangeLog

EXTRA_DIST = emu/gpmemu.texi emu/m6emu.texi emu/m4emu.texi emu/m0start.texi emu/gpm.m0 emu/m6.m0 emu/m4v7.m0 emu/m4posix.m0 emu/m4bsd.m0 emu/m4gnu.m0 emu/m0start.m0  emu/gpm.src emu/m4.src emu/m6.src emu/m0start.src emu/docs.m0 emu/emus.m0 doc/m0.pdf doc/m0algo.pdf
