AM_CFLAGS = -Winline -Wall -Wno-pointer-sign -Wno-unused-parameter
bin_PROGRAMS = m0
m0_SOURCES = main.c sds.c input.c xmalloc.c processor.c macros.c stack.c bitapvec.c exitcodes.c output.c statistics.c
include_HEADERS = definesizes.h sds.h input.h xmalloc.h processor.h macros.h stack.h bitapvec.h exitcodes.h output.h statistics.h sdsalloc.h